name: publish

on:
  push:
    branches:
      - main

jobs:
  Publish_Wiki:
    runs-on: ubuntu-22.04
    steps:
    # Checkout the server.wiki repo that we want to publish to with the GH_PAT token.
    # This allows us to push to it when we're ready with changes.
    - uses: actions/checkout@v3
      with:
        repository: zach2good/server.wiki.git
    - name: Fetch lsb-wiki changes
      run: |
        git remote add lsb-wiki https://github.com/zach2good/lsb-wiki.git
        git fetch lsb-wiki main:lsb-wiki
    - name: Add upstream remote
      run: |
        # Force-push local lsb-wiki branch onto server.wiki's master branch (this is the visible branch)
        git push --force origin lsb-wiki:master
